//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.24 at 03:44:55 PM BST 
//


package OctopusConsortium.Models.RCS;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for CHCCancellationReasonCode_displayName.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CHCCancellationReasonCode_displayName">
 *   &lt;restriction base="{urn:hl7-org:v3}st">
 *     &lt;enumeration value="The patient has died"/>
 *     &lt;enumeration value="The patient wishes to make their own care arrangements"/>
 *     &lt;enumeration value="The patient has moved out of area"/>
 *     &lt;enumeration value="The patient has withdrawn consent to the assessment process"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum CHCCancellationReasonCodeDisplayName {

    @XmlEnumValue("The patient has died")
    THE_PATIENT_HAS_DIED("The patient has died"),
    @XmlEnumValue("The patient wishes to make their own care arrangements")
    THE_PATIENT_WISHES_TO_MAKE_THEIR_OWN_CARE_ARRANGEMENTS("The patient wishes to make their own care arrangements"),
    @XmlEnumValue("The patient has moved out of area")
    THE_PATIENT_HAS_MOVED_OUT_OF_AREA("The patient has moved out of area"),
    @XmlEnumValue("The patient has withdrawn consent to the assessment process")
    THE_PATIENT_HAS_WITHDRAWN_CONSENT_TO_THE_ASSESSMENT_PROCESS("The patient has withdrawn consent to the assessment process");
    private final String value;

    CHCCancellationReasonCodeDisplayName(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CHCCancellationReasonCodeDisplayName fromValue(String v) {
        for (CHCCancellationReasonCodeDisplayName c: CHCCancellationReasonCodeDisplayName.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
