//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.24 at 03:44:55 PM BST 
//


package OctopusConsortium.Models.RCS;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for QUPA_MT000001GB01.RepeatCallerQuery complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QUPA_MT000001GB01.RepeatCallerQuery">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{urn:hl7-org:v3}InfrastructureRootElements"/>
 *         &lt;element name="code">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{urn:hl7-org:v3}CV">
 *                 &lt;attribute name="code" use="required" type="{urn:hl7-org:v3}cs" fixed="01" />
 *                 &lt;attribute name="codeSystem" use="required" type="{urn:hl7-org:v3}uid" fixed="2.16.840.1.113883.2.1.3.2.4.17.420" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="effectiveTime">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{urn:hl7-org:v3}TS">
 *                 &lt;attribute name="value" use="required" type="{urn:hl7-org:v3}ts" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="id" type="{urn:hl7-org:v3}II.NPfIT.uuid.mandatory"/>
 *         &lt;element name="author" type="{urn:hl7-org:v3}QUPA_MT000001GB01.Author"/>
 *         &lt;element name="query" type="{urn:hl7-org:v3}QUPA_MT000001GB01.Query"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{urn:hl7-org:v3}InfrastructureRootAttributes"/>
 *       &lt;attribute name="classCode" use="required" type="{urn:hl7-org:v3}cs" fixed="CACT" />
 *       &lt;attribute name="moodCode" use="required" type="{urn:hl7-org:v3}cs" fixed="EVN" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QUPA_MT000001GB01.RepeatCallerQuery", propOrder = {
    "code",
    "effectiveTime",
    "id",
    "author",
    "query"
})
public class QUPAMT000001GB01RepeatCallerQuery {

    @XmlElement(required = true)
    protected QUPAMT000001GB01RepeatCallerQuery.Code code;
    @XmlElement(required = true)
    protected QUPAMT000001GB01RepeatCallerQuery.EffectiveTime effectiveTime;
    @XmlElement(required = true)
    protected IINPfITUuidMandatory id;
    @XmlElement(required = true)
    protected QUPAMT000001GB01Author author;
    @XmlElement(required = true)
    protected QUPAMT000001GB01Query query;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String classCode;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String moodCode;
    @XmlAttribute
    protected List<String> nullFlavor;
    @XmlAttribute
    protected CsUpdateMode updateMode;

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link QUPAMT000001GB01RepeatCallerQuery.Code }
     *     
     */
    public QUPAMT000001GB01RepeatCallerQuery.Code getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link QUPAMT000001GB01RepeatCallerQuery.Code }
     *     
     */
    public void setCode(QUPAMT000001GB01RepeatCallerQuery.Code value) {
        this.code = value;
    }

    /**
     * Gets the value of the effectiveTime property.
     * 
     * @return
     *     possible object is
     *     {@link QUPAMT000001GB01RepeatCallerQuery.EffectiveTime }
     *     
     */
    public QUPAMT000001GB01RepeatCallerQuery.EffectiveTime getEffectiveTime() {
        return effectiveTime;
    }

    /**
     * Sets the value of the effectiveTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link QUPAMT000001GB01RepeatCallerQuery.EffectiveTime }
     *     
     */
    public void setEffectiveTime(QUPAMT000001GB01RepeatCallerQuery.EffectiveTime value) {
        this.effectiveTime = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link IINPfITUuidMandatory }
     *     
     */
    public IINPfITUuidMandatory getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link IINPfITUuidMandatory }
     *     
     */
    public void setId(IINPfITUuidMandatory value) {
        this.id = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link QUPAMT000001GB01Author }
     *     
     */
    public QUPAMT000001GB01Author getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link QUPAMT000001GB01Author }
     *     
     */
    public void setAuthor(QUPAMT000001GB01Author value) {
        this.author = value;
    }

    /**
     * Gets the value of the query property.
     * 
     * @return
     *     possible object is
     *     {@link QUPAMT000001GB01Query }
     *     
     */
    public QUPAMT000001GB01Query getQuery() {
        return query;
    }

    /**
     * Sets the value of the query property.
     * 
     * @param value
     *     allowed object is
     *     {@link QUPAMT000001GB01Query }
     *     
     */
    public void setQuery(QUPAMT000001GB01Query value) {
        this.query = value;
    }

    /**
     * Gets the value of the classCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassCode() {
        if (classCode == null) {
            return "CACT";
        } else {
            return classCode;
        }
    }

    /**
     * Sets the value of the classCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassCode(String value) {
        this.classCode = value;
    }

    /**
     * Gets the value of the moodCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMoodCode() {
        if (moodCode == null) {
            return "EVN";
        } else {
            return moodCode;
        }
    }

    /**
     * Sets the value of the moodCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMoodCode(String value) {
        this.moodCode = value;
    }

    /**
     * Gets the value of the nullFlavor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nullFlavor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNullFlavor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNullFlavor() {
        if (nullFlavor == null) {
            nullFlavor = new ArrayList<String>();
        }
        return this.nullFlavor;
    }

    /**
     * Gets the value of the updateMode property.
     * 
     * @return
     *     possible object is
     *     {@link CsUpdateMode }
     *     
     */
    public CsUpdateMode getUpdateMode() {
        return updateMode;
    }

    /**
     * Sets the value of the updateMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CsUpdateMode }
     *     
     */
    public void setUpdateMode(CsUpdateMode value) {
        this.updateMode = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{urn:hl7-org:v3}CV">
     *       &lt;attribute name="code" use="required" type="{urn:hl7-org:v3}cs" fixed="01" />
     *       &lt;attribute name="codeSystem" use="required" type="{urn:hl7-org:v3}uid" fixed="2.16.840.1.113883.2.1.3.2.4.17.420" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Code
        extends CV
    {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{urn:hl7-org:v3}TS">
     *       &lt;attribute name="value" use="required" type="{urn:hl7-org:v3}ts" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class EffectiveTime
        extends TS
    {


    }

}
