
package OctopusConsortium.DosService1_3;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-02-26T15:32:21.859Z
 * Generated source version: 3.0.4
 * 
 */
public final class PathWayServiceSoap_PathWayServiceSoap12_Client {

    private static final QName SERVICE_NAME = new QName("https://nww.pathwaysdos.nhs.uk/app/api/webservices", "PathWayService");

    private PathWayServiceSoap_PathWayServiceSoap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = PathWayService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        PathWayService ss = new PathWayService(wsdlURL, SERVICE_NAME);
        PathWayServiceSoap port = ss.getPathWayServiceSoap12();  
        
        {
        System.out.println("Invoking serviceAnalysis...");
        OctopusConsortium.DosService1_3.UserInfo _serviceAnalysis_userInfo = null;
        OctopusConsortium.DosService1_3.SACase _serviceAnalysis_c = null;
        javax.xml.ws.Holder<java.lang.String> _serviceAnalysis_transactionId = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<OctopusConsortium.DosService1_3.ArrayOfServiceAnalysisResults> _serviceAnalysis_serviceAnalysisResultArray = new javax.xml.ws.Holder<OctopusConsortium.DosService1_3.ArrayOfServiceAnalysisResults>();
        port.serviceAnalysis(_serviceAnalysis_userInfo, _serviceAnalysis_c, _serviceAnalysis_transactionId, _serviceAnalysis_serviceAnalysisResultArray);

        System.out.println("serviceAnalysis._serviceAnalysis_transactionId=" + _serviceAnalysis_transactionId.value);
        System.out.println("serviceAnalysis._serviceAnalysis_serviceAnalysisResultArray=" + _serviceAnalysis_serviceAnalysisResultArray.value);

        }
        {
        System.out.println("Invoking getHospitalScores...");
        OctopusConsortium.DosService1_3.UserInfo _getHospitalScores_userInfo = null;
        OctopusConsortium.DosService1_3.ArrayOfHospitalScores _getHospitalScores__return = port.getHospitalScores(_getHospitalScores_userInfo);
        System.out.println("getHospitalScores.result=" + _getHospitalScores__return);


        }
        {
        System.out.println("Invoking checkCapacitySummary...");
        OctopusConsortium.DosService1_3.UserInfo _checkCapacitySummary_userInfo = null;
        OctopusConsortium.DosService1_3.Case _checkCapacitySummary_c = null;
        javax.xml.ws.Holder<java.lang.String> _checkCapacitySummary_transactionId = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<OctopusConsortium.DosService1_3.ArrayOfServiceCareSummaryDestination> _checkCapacitySummary_checkCapacitySummaryResult = new javax.xml.ws.Holder<OctopusConsortium.DosService1_3.ArrayOfServiceCareSummaryDestination>();
        port.checkCapacitySummary(_checkCapacitySummary_userInfo, _checkCapacitySummary_c, _checkCapacitySummary_transactionId, _checkCapacitySummary_checkCapacitySummaryResult);

        System.out.println("checkCapacitySummary._checkCapacitySummary_transactionId=" + _checkCapacitySummary_transactionId.value);
        System.out.println("checkCapacitySummary._checkCapacitySummary_checkCapacitySummaryResult=" + _checkCapacitySummary_checkCapacitySummaryResult.value);

        }
        {
        System.out.println("Invoking exceptionCapture...");
        OctopusConsortium.DosService1_3.UserInfo _exceptionCapture_userInfo = null;
        OctopusConsortium.DosService1_3.ArrayOfExceptionCapture _exceptionCapture__return = port.exceptionCapture(_exceptionCapture_userInfo);
        System.out.println("exceptionCapture.result=" + _exceptionCapture__return);


        }
        {
        System.out.println("Invoking serviceDetailsById...");
        OctopusConsortium.DosService1_3.UserInfo _serviceDetailsById_userInfo = null;
        java.lang.String _serviceDetailsById_serviceId = "";
        OctopusConsortium.DosService1_3.ArrayOfServices _serviceDetailsById__return = port.serviceDetailsById(_serviceDetailsById_userInfo, _serviceDetailsById_serviceId);
        System.out.println("serviceDetailsById.result=" + _serviceDetailsById__return);


        }

        System.exit(0);
    }

}
