//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.11 at 01:11:57 PM BST 
//


package OctopusConsortium.Models.ITK;

import javax.xml.bind.annotation.XmlEnum;


/**
 * <p>Java class for ActRelationshipConditional_X.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ActRelationshipConditional_X">
 *   &lt;restriction base="{urn:hl7-org:v3}cs">
 *     &lt;enumeration value="CIND"/>
 *     &lt;enumeration value="PRCN"/>
 *     &lt;enumeration value="RSON"/>
 *     &lt;enumeration value="TRIG"/>
 *     &lt;enumeration value="RACT"/>
 *     &lt;enumeration value="SUGG"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum ActRelationshipConditionalX {

    CIND,
    PRCN,
    RSON,
    TRIG,
    RACT,
    SUGG;

    public String value() {
        return name();
    }

    public static ActRelationshipConditionalX fromValue(String v) {
        return valueOf(v);
    }

}
