//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.11 at 01:11:57 PM BST 
//


package OctopusConsortium.Models.ITK;

import javax.xml.bind.annotation.XmlEnum;


/**
 * <p>Java class for ActRelationshipSequel_X.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ActRelationshipSequel_X">
 *   &lt;restriction base="{urn:hl7-org:v3}cs">
 *     &lt;enumeration value="SEQL"/>
 *     &lt;enumeration value="DOC"/>
 *     &lt;enumeration value="ELNK"/>
 *     &lt;enumeration value="GEVL"/>
 *     &lt;enumeration value="GEN"/>
 *     &lt;enumeration value="OPTN"/>
 *     &lt;enumeration value="INST"/>
 *     &lt;enumeration value="APND"/>
 *     &lt;enumeration value="MTCH"/>
 *     &lt;enumeration value="REV"/>
 *     &lt;enumeration value="XFRM"/>
 *     &lt;enumeration value="UPDT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum ActRelationshipSequelX {

    SEQL,
    DOC,
    ELNK,
    GEVL,
    GEN,
    OPTN,
    INST,
    APND,
    MTCH,
    REV,
    XFRM,
    UPDT;

    public String value() {
        return name();
    }

    public static ActRelationshipSequelX fromValue(String v) {
        return valueOf(v);
    }

}
