//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.11 at 01:11:57 PM BST 
//


package OctopusConsortium.Models.ITK;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CV.NHS.CodedValueType1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CV.NHS.CodedValueType1">
 *   &lt;complexContent>
 *     &lt;restriction base="{urn:hl7-org:v3}CV">
 *       &lt;attribute name="code" use="required" type="{urn:hl7-org:v3}cs" />
 *       &lt;attribute name="codeSystem" use="required" type="{urn:hl7-org:v3}uid" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CV.NHS.CodedValueType1")
@XmlSeeAlso({
    OctopusConsortium.Models.ITK.COMTMT000016GB01GetPatientDetailsResponseV10 .Code.class,
    OctopusConsortium.Models.ITK.COMTMT000016GB01GetPatientDetailsResponseV10 .Value.class,
    OctopusConsortium.Models.ITK.COMTMT000016GB01Person.AdministrativeGenderCode.class
})
public class CVNHSCodedValueType1
    extends CV
{


}
