//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.07 at 10:56:57 AM BST 
//


package OctopusConsortium.Models.ITK;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the OctopusConsortium.Models.ITK package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DistributionEnvelope_QNAME = new QName("urn:nhs-itk:ns:201005", "DistributionEnvelope");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: OctopusConsortium.Models.ITK
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddressListType }
     * 
     */
    public AddressListType createAddressListType() {
        return new AddressListType();
    }

    /**
     * Create an instance of {@link DistributionHeaderType }
     * 
     */
    public DistributionHeaderType createDistributionHeaderType() {
        return new DistributionHeaderType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link PayloadsType }
     * 
     */
    public PayloadsType createPayloadsType() {
        return new PayloadsType();
    }

    /**
     * Create an instance of {@link DistributionEnvelopeType }
     * 
     */
    public DistributionEnvelopeType createDistributionEnvelopeType() {
        return new DistributionEnvelopeType();
    }

    /**
     * Create an instance of {@link ManifestItemType }
     * 
     */
    public ManifestItemType createManifestItemType() {
        return new ManifestItemType();
    }

    /**
     * Create an instance of {@link HandlingSpecType }
     * 
     */
    public HandlingSpecType createHandlingSpecType() {
        return new HandlingSpecType();
    }

    /**
     * Create an instance of {@link HandlingType }
     * 
     */
    public HandlingType createHandlingType() {
        return new HandlingType();
    }

    /**
     * Create an instance of {@link PayloadType }
     * 
     */
    public PayloadType createPayloadType() {
        return new PayloadType();
    }

    /**
     * Create an instance of {@link ManifestType }
     * 
     */
    public ManifestType createManifestType() {
        return new ManifestType();
    }

    /**
     * Create an instance of {@link IdentityType }
     * 
     */
    public IdentityType createIdentityType() {
        return new IdentityType();
    }

    /**
     * Create an instance of {@link AuditIdentityType }
     * 
     */
    public AuditIdentityType createAuditIdentityType() {
        return new AuditIdentityType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DistributionEnvelopeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:nhs-itk:ns:201005", name = "DistributionEnvelope")
    public JAXBElement<DistributionEnvelopeType> createDistributionEnvelope(DistributionEnvelopeType value) {
        return new JAXBElement<DistributionEnvelopeType>(_DistributionEnvelope_QNAME, DistributionEnvelopeType.class, null, value);
    }

}
