//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.24 at 11:01:41 AM BST 
//


package OctopusConsortium.Models.RCSGB;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for CHCRejectionReason_displayName.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CHCRejectionReason_displayName">
 *   &lt;restriction base="{urn:hl7-org:v3}st">
 *     &lt;enumeration value="Not eligible for Continuing Healthcare"/>
 *     &lt;enumeration value="Assessment sent to the incorrect person / team"/>
 *     &lt;enumeration value="Not eligible for Fast Track"/>
 *     &lt;enumeration value="Not enough information to complete the assessment"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum CHCRejectionReasonDisplayName {

    @XmlEnumValue("Not eligible for Continuing Healthcare")
    NOT_ELIGIBLE_FOR_CONTINUING_HEALTHCARE("Not eligible for Continuing Healthcare"),
    @XmlEnumValue("Assessment sent to the incorrect person / team")
    ASSESSMENT_SENT_TO_THE_INCORRECT_PERSON_TEAM("Assessment sent to the incorrect person / team"),
    @XmlEnumValue("Not eligible for Fast Track")
    NOT_ELIGIBLE_FOR_FAST_TRACK("Not eligible for Fast Track"),
    @XmlEnumValue("Not enough information to complete the assessment")
    NOT_ENOUGH_INFORMATION_TO_COMPLETE_THE_ASSESSMENT("Not enough information to complete the assessment");
    private final String value;

    CHCRejectionReasonDisplayName(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CHCRejectionReasonDisplayName fromValue(String v) {
        for (CHCRejectionReasonDisplayName c: CHCRejectionReasonDisplayName.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
