//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.24 at 11:01:41 AM BST 
//


package OctopusConsortium.Models.RCSGB;

import javax.xml.bind.annotation.XmlEnum;


/**
 * <p>Java class for DSTCareDomain_code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DSTCareDomain_code">
 *   &lt;restriction base="{urn:hl7-org:v3}cs">
 *     &lt;enumeration value="DSTBEH"/>
 *     &lt;enumeration value="DSTCOG"/>
 *     &lt;enumeration value="DSTPSY"/>
 *     &lt;enumeration value="DSTCOM"/>
 *     &lt;enumeration value="DSTMOB"/>
 *     &lt;enumeration value="DSTNUT"/>
 *     &lt;enumeration value="DSTCON"/>
 *     &lt;enumeration value="DSTSKI"/>
 *     &lt;enumeration value="DSTBRE"/>
 *     &lt;enumeration value="DSTMED"/>
 *     &lt;enumeration value="DSTCONS"/>
 *     &lt;enumeration value="DSTOSN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum DSTCareDomainCode {

    DSTBEH,
    DSTCOG,
    DSTPSY,
    DSTCOM,
    DSTMOB,
    DSTNUT,
    DSTCON,
    DSTSKI,
    DSTBRE,
    DSTMED,
    DSTCONS,
    DSTOSN;

    public String value() {
        return name();
    }

    public static DSTCareDomainCode fromValue(String v) {
        return valueOf(v);
    }

}
