//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.24 at 11:01:41 AM BST 
//


package OctopusConsortium.Models.RCSGB;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * An identifier that uniquely identifies a thing or object. Examples
 * are object identifier for HL7 RIM objects, medical record number,
 * order id, service catalog item id, Vehicle Identification Number
 * (VIN), etc. Instance identifiers are defined based on ISO object
 * identifiers.
 * 
 * 
 * <p>Java class for II complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="II">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:v3}ANY">
 *       &lt;attribute name="root" type="{urn:hl7-org:v3}uid" />
 *       &lt;attribute name="extension" type="{urn:hl7-org:v3}st" />
 *       &lt;attribute name="assigningAuthorityName" type="{urn:hl7-org:v3}st" />
 *       &lt;attribute name="displayable" type="{urn:hl7-org:v3}bl" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "II")
@XmlSeeAlso({
    OctopusConsortium.Models.RCSGB.COCDTP145214GB01AssociatedEntity.TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP146227GB02ServiceEvent.TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP146246GB01Section4 .TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP145212GB02Person.TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP146246GB01Section5 .TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP146246GB01Section2 .TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP146246GB01Section3 .TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP146246GB01Section6 .TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP146246GB01Section1 .TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP145214GB01Organization.Id.class,
    OctopusConsortium.Models.RCSGB.COCDTP145214GB01Organization.TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP146232GB01EncounterParticipant.TemplateId.class,
    POCDMT200001GB02ClinicalDocumentTypeId.class,
    OctopusConsortium.Models.RCSGB.COCDTP146246GB01Component.TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP145200GB01Organization.Id.class,
    OctopusConsortium.Models.RCSGB.COCDTP145200GB01Organization.TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP145210GB01AssignedEntity.TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP145200GB01AssignedAuthor.TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP145210GB01Person.TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP145203GB03IntendedRecipient.TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP145007UK03Person.TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP145000GB01ParticipantRole.TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP145212GB02Workgroup.TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP145222GB02Place.TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP145207GB01AssignedAuthorDevice.TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP145202GB02IntendedRecipient.TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP145007UK03RelatedEntity.TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP146232GB01EncompassingEncounter.TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP145212GB02Organization.Id.class,
    OctopusConsortium.Models.RCSGB.COCDTP145212GB02Organization.TemplateId.class,
    IINPfITUuidRequired.class,
    OctopusConsortium.Models.RCSGB.COCDTP145208GB01AssignedAuthor.TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP146232GB01Location.TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP145000GB01Device.TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP146246GB01Component5 .TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP146246GB01Component4 .TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP146246GB01Component3 .TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP146246GB01Component2 .TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP145200GB01Person.TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP145204GB03RecipientWorkgroup.TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP146002GB01ObservationMedia.TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP145208GB01Organization.Id.class,
    OctopusConsortium.Models.RCSGB.COCDTP145208GB01Organization.TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP146226GB02Consent.TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP145204GB03Person.TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP145201GB01Organization.Id.class,
    OctopusConsortium.Models.RCSGB.COCDTP145201GB01Organization.TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP145201GB01Patient.TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP145202GB02Person.TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP145201GB01LanguageCommunication.TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP145210GB01Organization.Id.class,
    OctopusConsortium.Models.RCSGB.COCDTP145210GB01Organization.TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP146002GB01Device.TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP145207GB01Organization.Id.class,
    OctopusConsortium.Models.RCSGB.COCDTP145207GB01Organization.TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP145201GB01PatientRole.TemplateId.class,
    IINPfITOidRequiredAssigningAuthorityName.class,
    OctopusConsortium.Models.RCSGB.COCDTP145018UK03AssignedCustodian.TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP145207GB01AuthoringDevice.TemplateId.class,
    IINPfITOidMandatoryAssignedAuthority.class,
    AllInfrastructureRootTypeId.class,
    OctopusConsortium.Models.RCSGB.COCDTP145204GB03Organization.Id.class,
    OctopusConsortium.Models.RCSGB.COCDTP145204GB03Organization.TemplateId.class,
    AllInfrastructureRootTemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP145202GB02Organization.Id.class,
    OctopusConsortium.Models.RCSGB.COCDTP145202GB02Organization.TemplateId.class,
    IINPfITOidRequired.class,
    OctopusConsortium.Models.RCSGB.COCDTP146227GB02Participant.TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP146246GB01Author1 .TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP145214GB01Person.TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP146232GB01ResponsibleParty.TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP145018UK03CustodianOrganization.Id.class,
    OctopusConsortium.Models.RCSGB.COCDTP145018UK03CustodianOrganization.TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP145203GB03Organization.Id.class,
    OctopusConsortium.Models.RCSGB.COCDTP145203GB03Organization.TemplateId.class,
    OctopusConsortium.Models.RCSGB.COCDTP145222GB02HealthCareFacility.TemplateId.class,
    MessageType.class,
    TemplateContent.class
})
public class II
    extends ANY
{

    @XmlAttribute
    protected String root;
    @XmlAttribute
    protected String extension;
    @XmlAttribute
    protected String assigningAuthorityName;
    @XmlAttribute
    protected Boolean displayable;

    /**
     * Gets the value of the root property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoot() {
        return root;
    }

    /**
     * Sets the value of the root property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoot(String value) {
        this.root = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtension(String value) {
        this.extension = value;
    }

    /**
     * Gets the value of the assigningAuthorityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssigningAuthorityName() {
        return assigningAuthorityName;
    }

    /**
     * Sets the value of the assigningAuthorityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssigningAuthorityName(String value) {
        this.assigningAuthorityName = value;
    }

    /**
     * Gets the value of the displayable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDisplayable() {
        return displayable;
    }

    /**
     * Sets the value of the displayable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDisplayable(Boolean value) {
        this.displayable = value;
    }

}
