//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.24 at 11:01:41 AM BST 
//


package OctopusConsortium.Models.RCSGB;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for NHS111AdditionalNotesType_displayName.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="NHS111AdditionalNotesType_displayName">
 *   &lt;restriction base="{urn:hl7-org:v3}st">
 *     &lt;enumeration value="Special Patient Notes"/>
 *     &lt;enumeration value="Location Access Information"/>
 *     &lt;enumeration value="Other Additional Notes"/>
 *     &lt;enumeration value="Primary Reason for Call - Chief Complaint in recipient systems"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum NHS111AdditionalNotesTypeDisplayName {

    @XmlEnumValue("Special Patient Notes")
    SPECIAL_PATIENT_NOTES("Special Patient Notes"),
    @XmlEnumValue("Location Access Information")
    LOCATION_ACCESS_INFORMATION("Location Access Information"),
    @XmlEnumValue("Other Additional Notes")
    OTHER_ADDITIONAL_NOTES("Other Additional Notes"),
    @XmlEnumValue("Primary Reason for Call \u2013 Chief Complaint in recipient systems")
    PRIMARY_REASON_FOR_CALL_CHIEF_COMPLAINT_IN_RECIPIENT_SYSTEMS("Primary Reason for Call \u2013 Chief Complaint in recipient systems");
    private final String value;

    NHS111AdditionalNotesTypeDisplayName(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static NHS111AdditionalNotesTypeDisplayName fromValue(String v) {
        for (NHS111AdditionalNotesTypeDisplayName c: NHS111AdditionalNotesTypeDisplayName.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
