//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.24 at 11:01:41 AM BST 
//


package OctopusConsortium.Models.RCSGB;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * The quantity data type is an abstract generalization for all data
 * types (1) whose value set has an order relation (less-or-equal) and
 * (2) where difference is defined in all of the data type's totally
 * ordered value subsets.  The quantity type abstraction is needed in
 * defining certain other types, such as the interval and the probability
 * distribution.
 * 
 * 
 * <p>Java class for QTY complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QTY">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:v3}ANY">
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QTY")
@XmlSeeAlso({
    MO.class,
    REAL.class,
    PQ.class,
    TS.class,
    RTOQTYQTY.Numerator.class,
    RTOQTYQTY.Denominator.class,
    RTOQTYQTY.class,
    INT.class
})
public abstract class QTY
    extends ANY
{


}
