//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.24 at 11:01:41 AM BST 
//


package OctopusConsortium.Models.RCSGB;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for ReasonForDocumentNullification_displayName.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ReasonForDocumentNullification_displayName">
 *   &lt;restriction base="{urn:hl7-org:v3}st">
 *     &lt;enumeration value="Sent in error"/>
 *     &lt;enumeration value="Sent to wrong patient record"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum ReasonForDocumentNullificationDisplayName {

    @XmlEnumValue("Sent in error")
    SENT_IN_ERROR("Sent in error"),
    @XmlEnumValue("Sent to wrong patient record")
    SENT_TO_WRONG_PATIENT_RECORD("Sent to wrong patient record");
    private final String value;

    ReasonForDocumentNullificationDisplayName(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ReasonForDocumentNullificationDisplayName fromValue(String v) {
        for (ReasonForDocumentNullificationDisplayName c: ReasonForDocumentNullificationDisplayName.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
