//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.26 at 11:11:57 AM BST 
//


package OctopusConsortium.Service.Models;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for Gender.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Gender">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Not_Known"/>
 *     &lt;enumeration value="Male"/>
 *     &lt;enumeration value="Female"/>
 *     &lt;enumeration value="Not_Specified"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum Gender {

    @XmlEnumValue("Not_Known")
    NOT_KNOWN("0"),
    @XmlEnumValue("Male")
    MALE("1"),
    @XmlEnumValue("Female")
    FEMALE("2"),
    @XmlEnumValue("Not_Specified")
    NOT_SPECIFIED("9");
    private final String value;

    Gender(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Gender fromValue(String v) {
        for (Gender c: Gender.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
    
    @Override
    public String toString() {        	
    	switch (this) {
		case NOT_KNOWN:
			return "Not known";		
		case FEMALE: 
			return "Female";
		case MALE:
			return "Male";
		case NOT_SPECIFIED:
			return "Not specified";
		default:
			return "Not specified";
		}		
    }

}
