//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.26 at 11:56:14 AM BST 
//


package OctopusConsortium.Service.Models;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for RepeatCallerStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RepeatCallerStatus">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Patient_is_repeat_caller"/>
 *     &lt;enumeration value="Patient_is_not_repeat_caller"/>
 *     &lt;enumeration value="Undetermined"/>
 *     &lt;enumeration value="Insufficient_Information"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum RepeatCallerStatus {

    @XmlEnumValue("Patient_is_repeat_caller")
    PATIENT_IS_REPEAT_CALLER("Patient_is_repeat_caller"),
    @XmlEnumValue("Patient_is_not_repeat_caller")
    PATIENT_IS_NOT_REPEAT_CALLER("Patient_is_not_repeat_caller"),
    @XmlEnumValue("Undetermined")
    UNDETERMINED("Undetermined"),
    @XmlEnumValue("Insufficient_Information")
    INSUFFICIENT_INFORMATION("Insufficient_Information");
    private final String value;

    RepeatCallerStatus(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RepeatCallerStatus fromValue(String v) {
        for (RepeatCallerStatus c: RepeatCallerStatus.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}