//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.12 at 02:51:14 PM BST 
//


package OctopusConsortium.Models.PathwaysCase2_4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="finalDispCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="finalDisptext" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="override" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Higher"/>
 *               &lt;enumeration value="Lower"/>
 *               &lt;enumeration value="CallerUnlikelyToFollow"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "finalDispCode",
    "finalDisptext",
    "override"
})
public class FinalDisposition {

    @XmlElement(required = true)
    protected String finalDispCode;
    @XmlElement(required = true)
    protected String finalDisptext;
    protected String override;

    /**
     * Gets the value of the finalDispCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinalDispCode() {
        return finalDispCode;
    }

    /**
     * Sets the value of the finalDispCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinalDispCode(String value) {
        this.finalDispCode = value;
    }

    /**
     * Gets the value of the finalDisptext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinalDisptext() {
        return finalDisptext;
    }

    /**
     * Sets the value of the finalDisptext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinalDisptext(String value) {
        this.finalDisptext = value;
    }

    /**
     * Gets the value of the override property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOverride() {
        return override;
    }

    /**
     * Sets the value of the override property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOverride(String value) {
        this.override = value;
    }

}
