//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.12 at 02:51:14 PM BST 
//


package OctopusConsortium.Models.PathwaysCase2_4;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="systemFlag">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Trauma"/>
 *               &lt;enumeration value="NonTrauma"/>
 *               &lt;enumeration value="SceneSafe"/>
 *               &lt;enumeration value="SceneUnsafe"/>
 *               &lt;enumeration value="Police"/>
 *               &lt;enumeration value="Fire"/>
 *               &lt;enumeration value="CATALevel1"/>
 *               &lt;enumeration value="CATALevel2"/>
 *               &lt;enumeration value="CATALevel3"/>
 *               &lt;enumeration value="CATALevel4"/>
 *               &lt;enumeration value="CATBLevel1"/>
 *               &lt;enumeration value="CATBLevel2"/>
 *               &lt;enumeration value="CATBLevel3"/>
 *               &lt;enumeration value="CATBLevel4"/>
 *               &lt;enumeration value="Trapped"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "systemFlag"
})
public class SystemFlags {

    @XmlElement(required = true)
    protected List<SystemFlag> systemFlag;

    /**
     * Gets the value of the systemFlag property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the systemFlag property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSystemFlag().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<SystemFlag> getSystemFlag() {
        if (systemFlag == null) {
            systemFlag = new ArrayList<SystemFlag>();
        }
        return this.systemFlag;
    }

}
