//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.07 at 10:56:02 AM BST 
//


package OctopusConsortium.Models.PDS;

import javax.xml.bind.annotation.XmlEnum;


/**
 * <p>Java class for ActRelationshipOutcome_X.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ActRelationshipOutcome_X">
 *   &lt;restriction base="{urn:hl7-org:v3}cs">
 *     &lt;enumeration value="RISK"/>
 *     &lt;enumeration value="OBJC"/>
 *     &lt;enumeration value="OUTC"/>
 *     &lt;enumeration value="OBJF"/>
 *     &lt;enumeration value="GOAL"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum ActRelationshipOutcomeX {

    RISK,
    OBJC,
    OUTC,
    OBJF,
    GOAL;

    public String value() {
        return name();
    }

    public static ActRelationshipOutcomeX fromValue(String v) {
        return valueOf(v);
    }

}
