package OctopusConsortium.PDSMiniServicesV1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-09-11T14:29:56.784+01:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "urn:nhs-itk:ns:201005", name = "getNHSNumber-v1-0_ptt")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GetNHSNumberV10Ptt {

    @WebResult(name = "DistributionEnvelope", targetNamespace = "urn:nhs-itk:ns:201005", partName = "getNHSNumberResponse-v1-0")
    @WebMethod(operationName = "getNHSNumber-v1-0", action = "urn:nhs-itk:services:201005:getNHSNumber-v1-0")
    public DistributionEnvelopeType getNHSNumberV10(
        @WebParam(partName = "getNHSNumberRequest-v1-0", name = "DistributionEnvelope", targetNamespace = "urn:nhs-itk:ns:201005")
        DistributionEnvelopeType getNHSNumberRequestV10
    ) throws FaultResponse;
}
