package OctopusConsortium.PDSMiniServicesV1;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-09-11T14:29:56.846+01:00
 * Generated source version: 2.6.2
 * 
 */
@WebServiceClient(name = "getNHSNumber-v1-0", 
                  wsdlLocation = "file:PDSMiniServices/wsdl/PDSMiniServices-v1-0.wsdl",
                  targetNamespace = "urn:nhs-itk:ns:201005") 
public class GetNHSNumberV10 extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:nhs-itk:ns:201005", "getNHSNumber-v1-0");
    public final static QName GetNHSNumberV10PttPort = new QName("urn:nhs-itk:ns:201005", "getNHSNumber-v1-0_pttPort");
    static {
        URL url = null;
        try {
            url = new URL("PDSMiniServices/wsdl/PDSMiniServices-v1-0.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GetNHSNumberV10.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:PDSMiniServices/wsdl/PDSMiniServices-v1-0.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GetNHSNumberV10(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GetNHSNumberV10(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetNHSNumberV10() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns GetNHSNumberV10Ptt
     */
    @WebEndpoint(name = "getNHSNumber-v1-0_pttPort")
    public GetNHSNumberV10Ptt getGetNHSNumberV10PttPort() {
        return super.getPort(GetNHSNumberV10PttPort, GetNHSNumberV10Ptt.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetNHSNumberV10Ptt
     */
    @WebEndpoint(name = "getNHSNumber-v1-0_pttPort")
    public GetNHSNumberV10Ptt getGetNHSNumberV10PttPort(WebServiceFeature... features) {
        return super.getPort(GetNHSNumberV10PttPort, GetNHSNumberV10Ptt.class, features);
    }

}
