package OctopusConsortium.PDSMiniServicesV1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.soap.Addressing;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-09-11T14:29:56.737+01:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "urn:nhs-itk:ns:201005", name = "getPatientDetails-v1-0_ptt")
@XmlSeeAlso({ObjectFactory.class,OctopusConsortium.Models.PDS.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@Addressing(enabled=true,required=false)
public interface GetPatientDetailsV10Ptt {

    @WebResult(name = "DistributionEnvelope", targetNamespace = "urn:nhs-itk:ns:201005", partName = "getPatientDetailsResponse-v1-0")
    @WebMethod(operationName = "getPatientDetails-v1-0", action = "urn:nhs-itk:services:201005:getPatientDetails-v1-0")
    public DistributionEnvelopeType getPatientDetailsV10(
        @WebParam(partName = "getPatientDetailsRequest-v1-0", name = "DistributionEnvelope", targetNamespace = "urn:nhs-itk:ns:201005")
        DistributionEnvelopeType getPatientDetailsRequestV10
    ) throws FaultResponse;
}
