package OctopusConsortium.RepeatCallerServiceV1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.soap.Addressing;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-09-20T12:44:15.262+01:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "urn:nhs-itk:ns:201005", name = "NHS111RepeatCallerSyncQueryResp-v1-0_ptt")
@XmlSeeAlso({ObjectFactory.class,OctopusConsortium.Models.RCS.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@Addressing(enabled=true,required=true)
public interface NHS111RepeatCallerSyncQueryRespV10Ptt {

    @WebResult(name = "DistributionEnvelope", targetNamespace = "urn:nhs-itk:ns:201005", partName = "NHS111RepeatCallerResponse-v1-0")
    @Action(input = "urn:nhs-itk:services:201005:NHS111RepeatCallerSyncQueryResp-v1-0", output = "urn:nhs-itk:ns:201005/NHS111RepeatCallerSyncQueryResp-v1-0_ptt/NHS111RepeatCallerSyncQueryResp-v1-0Response", fault = {@FaultAction(className = NHS111RepeatCallerSyncQueryRespV10PttNHS111RepeatCallerSyncQueryRespV10ToolkitErrorInfoFaultMessage.class, value = "http://www.w3.org/2005/08/addressing/soap/fault")})
    @WebMethod(operationName = "NHS111RepeatCallerSyncQueryResp-v1-0", action = "urn:nhs-itk:services:201005:NHS111RepeatCallerSyncQueryResp-v1-0")
    public DistributionEnvelopeType nhs111RepeatCallerSyncQueryRespV10(
        @WebParam(partName = "NHS111RepeatCallerQuery-v1-0", name = "DistributionEnvelope", targetNamespace = "urn:nhs-itk:ns:201005")
        DistributionEnvelopeType nhs111RepeatCallerQueryV10
    ) throws NHS111RepeatCallerSyncQueryRespV10PttNHS111RepeatCallerSyncQueryRespV10ToolkitErrorInfoFaultMessage;
}
