package OctopusConsortium.RepeatCallerServiceV1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-09-20T12:44:15.247+01:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "urn:nhs-itk:ns:201005", name = "RequestAmbulanceDispatch-v2-0_ptt")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RequestAmbulanceDispatchV20Ptt {

    @WebResult(name = "SimpleMessageResponse", targetNamespace = "urn:nhs-itk:ns:201005", partName = "acknowledgementResponse")
    @Action(input = "urn:nhs-itk:services:201005:RequestAmbulanceDispatch-v2-0", output = "urn:nhs-itk:ns:201005/RequestAmbulanceDispatch-v2-0_ptt/RequestAmbulanceDispatch-v2-0Response", fault = {@FaultAction(className = RequestAmbulanceDispatchV20PttRequestAmbulanceDispatchV20ToolkitErrorInfoFaultMessage.class, value = "http://www.w3.org/2005/08/addressing/soap/fault")})
    @WebMethod(operationName = "RequestAmbulanceDispatch-v2-0", action = "urn:nhs-itk:services:201005:RequestAmbulanceDispatch-v2-0")
    public java.lang.String requestAmbulanceDispatchV20(
        @WebParam(partName = "RequestAmbulanceDispatch-v2-0", name = "DistributionEnvelope", targetNamespace = "urn:nhs-itk:ns:201005")
        DistributionEnvelopeType requestAmbulanceDispatchV20
    ) throws RequestAmbulanceDispatchV20PttRequestAmbulanceDispatchV20ToolkitErrorInfoFaultMessage;
}
